### ISSUE TITLE
NPE während Suche

### ISSUE THREAD

**Issue by kornherp** [DecentralizedAmateurPagingNetwork/DAPNETApp#69]
Hallo,

ich fürchte, ich habe einen Bug und einen UI f*ckup gefunden.

Reproduktion:

1) Öffnen der DAPNET App
2) Menü->Rubrics
3) Suchfeld: Eingabe "franken"
-> Ergebnisliste  lt. Screenshot "scrambled"
4) Suchergebnis anklicken
5) Neue Eingabe ins Suchfeld,
-> NPE beim ersten Buchstaben

Stacktrace:
11-16 10:44:45.598 17316 17389 W Filter  : An exception occured during performFiltering()!
11-16 10:44:45.598 17316 17389 W Filter  : java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String de.hampager.dap4j.models.News.getOwnerName()' on a null object reference
11-16 10:44:45.598 17316 17389 W Filter  : 	at de.hampager.dapnetmobile.filters.RubricContentFilter.performFiltering(RubricContentFilter.java:32)
11-16 10:44:45.598 17316 17389 W Filter  : 	at android.widget.Filter$RequestHandler.handleMessage(Filter.java:234)
11-16 10:44:45.598 17316 17389 W Filter  : 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-16 10:44:45.598 17316 17389 W Filter  : 	at android.os.Looper.loop(Looper.java:154)
11-16 10:44:45.598 17316 17389 W Filter  : 	at android.os.HandlerThread.run(HandlerThread.java:61)
11-16 10:44:45.630 17316 17316 D AndroidRuntime: Shutting down VM
11-16 10:44:45.634 17316 17316 E AndroidRuntime: FATAL EXCEPTION: main
11-16 10:44:45.634 17316 17316 E AndroidRuntime: Process: de.hampager.dapnetmobile, PID: 17316
11-16 10:44:45.634 17316 17316 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
11-16 10:44:45.634 17316 17316 E AndroidRuntime: 	at de.hampager.dapnetmobile.adapters.RubricContentAdapter.getItemCount(RubricContentAdapter.java:57)

![photo6014719124292349282](https://user-images.githubusercontent.com/10560448/48614075-aacca900-e98d-11e8-8c54-57cfb9e4d5ea.jpg)

**Comment by IHFSchwarz** [comment]
Danke für den report, werde es mir nächste Woche anschauen!
